### ISSUE TITLE
TypeError when starting default template on the web platform (-p web)

### ISSUE THREAD

**Issue by hlz** [flexn-io/flexn#22]
I'm investigating this project and I'm loving it so far. Really interested in the focusManager solution you've build.

Right now I'm trying to run the default example created with `rnv new --projectTemplate @flexn/template` on the web platform with `rnv run -p web`.

Out of the box it fails on my machine with:

`TypeError: (0 , helpers_1.Ratio) is not a function
    at eval (webpack-internal:///./node_modules/@flexn/sdk/lib/focusManager/constants.js:36:52)
    at Object../node_modules/@flexn/sdk/lib/focusManager/constants.js (/Users/hlz/Code/apps/flexn/test3/platformBuilds/app_web/.next/server/pages/_app.js:5443:1)`

Please let me know if I need to provide more information.

**Comment by hlz** [comment]
Thanks @aurimasmi, I'm going to try that version. Right now I'm investigating if Flexn SDK can and should be integrated in our existing TV apps. It looks very promising but it's also a lot of work for us to integrate. Will definitely hit you guys up if we've got questions.

**Comment by pauliusguzas** [comment]
Not repro on @flexn/template@0.18.0-alpha.8. Feel free to reopen if you experience this issue again
