### ISSUE TITLE
[iOS]  Chromecast modal window opens, but it doesn't take all screen on flexn/template

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/flexn#29]
rnv version: 0.36.1-canary.2
flexn template version: 0.16.0

How to repro:
1. Have app running on iOS
2. Click on chromecast icon
3. Observe -> chromecast modal window opens, but it doesn't take all screen

Expected: chromecast pop up should cover content which is behind

<img width="315" alt="Screenshot 2022-02-02 at 14 08 20" src="https://user-images.githubusercontent.com/66240948/152165866-e33fae74-c1da-46bf-8744-2897c37ebcc0.png">

**Comment by locksten** [comment]
Could not reproduce with:
- rnv v0.36.1-canary.2
- flexn template v0.16.0
- iOS 15.0, iOS 15.5

**Comment by pauliusguzas** [comment]
Not repro on:

- rnv v0.36.2-canary.4
- flexn template v0.17.0
