### ISSUE TITLE
[AndroidTV, fireTV] flexn/template has badly styled app icon

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/flexn#31]
rnv version: 0.36.1-canary.2
flexn template version: 0.16.0

How to repro:
1. Install app on device
2. Navigate to device home page to see all apps

Expected: App icon is styled properly

AndroidTV current icon:
![Screenshot 2022-06-23 at 09 54 42](https://user-images.githubusercontent.com/65670660/175234840-0ef74ab3-5d36-4bbb-b739-3065445da233.png)

fireTV current icon:
![153580627-8ceb6739-d18b-413e-b8a4-e45667a10a18](https://user-images.githubusercontent.com/65670660/172390471-d673473c-1c73-49f9-bfbf-2613d6c6722c.jpeg)

**Comment by locksten** [comment]
Could not reproduce on emulators:
- rnv 0.36.1-canary.2
- flexn template v0.16.0
- androidtv, firetv
- Android API 22, 28

**Comment by aurimasmi** [comment]
qa to be checked if it's still the case

**Comment by pauliusguzas** [comment]
Can't test firetv as there is a [bug](https://github.com/flexn-io/flexn/issues/24) but atv still has this issue on rnv 0.36.2-canary.4 and flexn/template 0.18.0-alpha.4

**Comment by locksten** [comment]
Running @flexn/template@0.18.0-alpha.4 with rnv@0.36.2-canary.4 on a tvOS 15.4 simulator, I get this (could it be a simulator vs device difference? Or am I running it somehow differently?):
<img width="1125" alt="Screen Shot 2022-09-09 at 16 50 13" src="https://user-images.githubusercontent.com/9592076/189366114-2fdc8370-6e74-4453-84a5-5ba57670bac2.png">
<img width="1125" alt="Screen Shot 2022-09-09 at 16 50 20" src="https://user-images.githubusercontent.com/9592076/189366127-0a8a9fb6-21c7-4936-91fb-b1e61bee0d3e.png">

**Comment by pauliusguzas** [comment]
@locksten I think we are running templates in some different way (my template always shows package.json version while yours I see is template version). I am installing correct rnv version, then doing rnv new, then selecting @flexn/template, then choosing certain version, and then simply running it

**Comment by locksten** [comment]
I did what you described @pauliusguzas and still didn't experience the problem 🤷 

![tv icon](https://user-images.githubusercontent.com/9592076/189630690-542fbba0-88fc-4667-8e1f-3585cf9d94a0.png)
![tvos icon 1](https://user-images.githubusercontent.com/9592076/189630737-f45ac1e2-f5e2-4a46-8271-3f13907f7df1.png)
![tvos icon 2](https://user-images.githubusercontent.com/9592076/189630746-1dfaa44a-21f2-4c81-bddc-130c6a32031f.png)
<img width="1551" alt="androidtv icon 1" src="https://user-images.githubusercontent.com/9592076/189630758-234160d3-19f6-4d0f-81f4-78637ea06806.png">
<img width="1551" alt="android tv icon 2" src="https://user-images.githubusercontent.com/9592076/189630769-25d92816-5133-48e1-aa82-8eb8659a5b03.png">

**Comment by locksten** [comment]
Reproduced on Android TV 10

![Screen Shot 2022-09-16 at 10 53 30](https://user-images.githubusercontent.com/9592076/190586564-cd24f5cf-4dd0-40fd-a0d6-8adfecb21531.png)

**Comment by aurimasmi** [comment]
Latest renative needs to be implemented and New deployments is needed utilising our new release pipelines
