### ISSUE TITLE
[Regression] [tvOS, AndroidTV, fireTV] returning from Details screen on @flexn/template opens TV Drawer

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/flexn#40]
rnv version: 0.36.2-canary.4
flexn template version: 0.17.0

How to repro:
1. Navigate to Details screen
2. Click on "Go back" or "Go to home"
3. TV Drawer opens

Expected: Carousel screen or Home screen opens

**Comment by aurimasmi** [comment]
New deployments is needed utilising our new release pipelines
