### ISSUE TITLE
[AndroidTV] No pictures are loaded on @flexn/template on AndroidTV 10

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/flexn#41]
rnv version: 0.36.2-canary.4
flexn template version: 0.17.0
AndroidtTV 10 (not repro on 8, 9, 11)

How to repro:
1. Navigate to Carousel screen -> no pictures
<img width="1245" alt="Screenshot 2022-09-12 at 10 41 57" src="https://user-images.githubusercontent.com/65670660/189879495-66710fe0-e7f9-443a-9c13-0bd7287b8cd0.png">
2. Navigate to Details screen -> no pictures
<img width="1245" alt="Screenshot 2022-09-12 at 10 41 57" src="https://user-images.githubusercontent.com/65670660/189880115-cfa1c248-e906-4e2d-9dd3-d80e0c179282.png">
Expected: Cat pictures should be visible

**Comment by locksten** [comment]
@pauliusguzas  tried running both directly in the flexn repo and with `rnv new`, could not reproduce.

<img width="400" alt="images not loading 0" src="https://user-images.githubusercontent.com/9592076/190585387-51606f84-24dd-40dc-b679-73c5e19765e0.png">

![images not loading 1](https://user-images.githubusercontent.com/9592076/190585402-efa672af-b742-4511-b2ca-a6010bccc0e5.png)

![images not loading 2](https://user-images.githubusercontent.com/9592076/190585395-c0ad1cfe-fb29-4105-b42a-3fb92734efce.png)

![images not loading 3](https://user-images.githubusercontent.com/9592076/190585390-086a659e-a25b-4d49-860a-7a036a11304d.png)

![images not loading 4](https://user-images.githubusercontent.com/9592076/190585398-9066534b-4150-4965-a243-fdda6f918b67.png)

**Comment by locksten** [comment]
Most likely caused by emulators being unreliable, @pauliusguzas will try cold booting before closing this

**Comment by pauliusguzas** [comment]
After cold boot issue was resolved on both my and @GabrieleKaceviciute machine
