### ISSUE TITLE
Clicking on "Rows" button in Harness app causes crash

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/flexn#43]
ReNative Version: 0.36.0-canary.13
Project Version ($package.version): 0.15.0-alpha.1

All platforms

**How to repro:**
1. Open app
2. Click on "Rows" -> crash

![Screenshot 2022-06-03 at 12 57 21](https://user-images.githubusercontent.com/65670660/171832912-6b51ee42-8624-42c8-9e3f-1dd732159810.png)

**Comment by mihaiblaga89** [comment]
@pauliusguzas can you recheck this please and close it if not applicable anymore? Thanks

**Comment by pauliusguzas** [comment]
Can't be tested due to [this](https://github.com/flexn-io/flexn/issues/48) however is fixed by [this](https://github.com/flexn-io/flexn/pull/46) and as we agreed we are closing issues which are fixed but not released @mihaiblaga89
