### ISSUE TITLE
[tvOS, AndroidTV] Template test scheme build can't be launched with "bundleAssets": true

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/flexn#44]
ReNative Version: 0.36.0-canary.13
Project Version ($package.version): 0.15.0

How to repro:
1. Do `yarn e2e-template-tvos` or `yarn e2e-template-androidtv` -> error

This is how test scheme looks:
```
"test": {
                    "signingConfig": "Debug",
                    "bundleAssets": true
                },
```

<img width="1243" alt="Screenshot 2022-06-06 at 12 18 56" src="https://user-images.githubusercontent.com/65670660/172133270-369b1ced-ccc5-42fa-b67e-ed31e02f8043.png">

<img width="1467" alt="Screenshot 2022-06-06 at 12 16 31" src="https://user-images.githubusercontent.com/65670660/172133250-27ecbd20-5470-48fa-9b80-d40af23f574e.png">

Related to https://github.com/renative-org/renative/issues/876

**Comment by locksten** [comment]
Same fix applies to `@rnv/template-starter` ([PR](https://github.com/renative-org/renative/pull/916))

**Comment by aurimasmi** [comment]
New deployments is needed utilising our new release pipeline
